on:
  pull_request:
  workflow_dispatch:
    inputs:
      skip:
        type: boolean
        description: Skip the steps

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"
      - if: ${{ github.event.inputs.skip == 'true' }}
        run: |
          echo "Im not skipped"
      - run: |
          echo "finish"
        
