on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app
    steps:
      - uses: actions/checkout@v4
      - run: yarn && yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: web-app/.next/

  custom:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action/test-artifact
