on: [push, pull_request]

name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.ref }}-${{ github.workflow }}"
          sleep 12
